apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
  namespace: anshi-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      name: springbootpod
      labels:
        app: springbootapp
    spec:
      containers:
      - name: springbootcont
        image: dockerhandson/spring-boot-mongo:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
  namespace: anshi-ns
spec:
  selector:
    app: springbootapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31117
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodeployment
  namespace: anshi-ns
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongopod
      labels:
        app: mongo
    spec:
      containers:
      - name: mongocont
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: anshi-ns
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017

